name: Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /home/ubuntu/geekshubs-library && git pull origin main  && docker-compose restart
          host: ${{ secrets.HOST }}
          username: ubuntu
          # passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true